# Generated by Django 3.2.6 on 2021-08-26 00:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('code', models.CharField(db_index=True, max_length=3, primary_key=True, serialize=False, verbose_name='商品コード')),
                ('name', models.CharField(max_length=100, verbose_name='商品名')),
                ('explanation', models.CharField(max_length=300, verbose_name='商品説明')),
                ('price', models.IntegerField(default=0, verbose_name='商品価格')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('create_user', models.CharField(blank=True, max_length=10, null=True, verbose_name='作成者')),
                ('update_user', models.CharField(blank=True, max_length=10, null=True, verbose_name='更新者')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='商品画像')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='r_prdct_img', to='product.product', verbose_name='商品情報')),
            ],
        ),
    ]
